language:
  python

python: 3.7
dist: xenial
sudo: true

install:
  - pip install -q tensorflow==2.0.0-alpha0
  - pip install -r requirements.txt -q

script:
  - export PYTHONPATH="$PYTHONPATH:$PWD"
  - export PYTHONPATH="${PYTHONPATH}:/home/travis/build/p-christ/nn_builder/tests"
  - export PYTHONPATH="${PYTHONPATH}:/home/travis/build/p-christ/nn_builder"
  - python -m pytest /home/travis/build/p-christ/nn_builder/tests/











