language:
  python

python: 3.7
dist: xenial
sudo: true

install:
  - pip install numpy -q
  - pip install torch -q

script:
  - export PYTHONPATH="$PYTHONPATH:$PWD"
  - export PYTHONPATH="${PYTHONPATH}:/home/travis/build/p-christ/Neural-Network-Builder/Tests"
  - export PYTHONPATH="${PYTHONPATH}:/home/travis/build/p-christ/Neural-Network-Builder"
  - pytest Tests/*.py











